# Generated by Django 4.2.2 on 2023-06-15 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(upload_to='authentication/image/'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
