# Generated by Django 4.2.2 on 2023-06-20 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_remove_customuser_otp_otp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otp',
            old_name='otp',
            new_name='otp_code',
        ),
    ]
